# Define job to build and publish Docker images
build-and-push-docker-image:
  needs: test-backend
  # Run only when code is compiling and tests are passing
  runs-on: ubuntu-24.04

  # Steps to perform in job
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        # Relative path to the place where source code with Dockerfile is located
        context: ./tp2/tp2/simple-api
        push: true
        # Note: tags must be all lower-case
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: ./tp2/tp2/database
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: ./tp2/tp2/httpd
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
