name: CI DevOps 2025

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuration de Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build et test Maven
      - name: Build and test with Maven
        run: mvn clean verify -f tp2/tp2/simple-api/pom.xml

  # 🚀 Define job to build and publish Docker images
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔐 Connexion Docker Hub AVANT le build/push
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./tp2/tp2/simple-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./tp2/tp2/database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./tp2/tp2/http-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest

