name: CI DevOps 2025

on:
  push:
    branches: [ main, develop ]  # Lance sur main et develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest  # Alpine n'est pas supporté ici
    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuration de Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build et test Maven
      - name: Build and test with Maven
        run: mvn clean verify

