name: CI DevOps 2025

on:
  push:
    branches: [ main ]
     paths-ignore:
      - 'flask-app/'
      - 'tp1/'
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configuration de Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build et test Maven
      - name: Build and test with Maven
        run: mvn clean verify

